### ISSUE TITLE
Add this

### ISSUE THREAD

**Issue by TheCuteOwl** [nanom/PyObfuscator#1]
https://github.com/TheCuteOwl/PyObfuscator-Deobfuscator

I've made a deobfuscator

add this somewhere in the readme plz

**Comment by nanom** [comment]
Hi how are you. Thanks for viewing my code. I left you some suggestions in your [issues section](https://github.com/TheCuteOwl/PyObfuscator-Deobfuscator/issues/1). 
Regards!
